### PR TITLE
Go Implementation Added

### PR DESCRIPTION
**Pull request by LordRahl90**
An Implementation of golang is added to the implementations....

### CODE REVIEW

**Comment by Youngestdev** [comment]
Hi @LordRahl90 , the go script can't be found .besides binary files are suppose to be hidden.

**Comment by LordRahl90** [comment]
i dropped the go scripts in another folder, just in case another person wants to upload an implementation.
As for the binary file, i am adding it to gitignore...

Thanks

**Comment by LordRahl90** [comment]
I will be closing this PR and send another...

**Comment by Youngestdev** [comment]
Great !. Meanwhile we can only have one Implementation, you either improve the code at #12 or write a better one.

**Pull request closed without merging**
