### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by Youngestdev**
Added @adejaremola to the contributor section.

### CODE REVIEW

**Comment by Youngestdev** [comment]
Thanks !

**Comment by Youngestdev** [comment]
@0sc , I'm available for merging and reviewing !

**Comment by 0sc** [comment]
Awesome @Youngestdev, I'll leave that to you then 🙌

**Comment by Youngestdev** [comment]
Yes.. Write access will be needed 😊😊😊

**Comment by 0sc** [comment]
@Youngestdev you should have write access; could you confirm?

**Comment by Youngestdev** [comment]
A minute please

**Comment by Youngestdev** [comment]
Okay cool ! Thanks @0sc

**Pull request merged**
